site_name: "Run Away"
theme:
  name: material
  language: pt
  logo: images/icon.png
  favicon: images/icon.png
  features:
    - navigation.instant
  palette:
    primary: purple
    accent: purple

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Ambiete de desenvolvimento: ambiente.md
  - Algoritmo do jogo: code.md
  - Questões da lista:
      - Questão 11: questoes/q11.md
      - Questão 18: questoes/q18.md
